/**
 * export consts for the Scan Reducer
 */

export const ANO_TAG_SCANNED_SUCCESS = 'ANO_TAG_SCANNED_SUCCESS'
export const ANO_TAG_SCANNED_FAILURE = 'ANO_TAG_SCANNED_FAILURE'
export const ANO_NUMBER_BAR_CODES = 'ANO_NUMBER_BAR_CODES'
export const ANO_PRINT_BAR_CODES = 'ANO_PRINT_BAR_CODES'
export const ANO_CLOSE_MODAL = 'ANO_CLOSE_MODAL'
export const ANO_SHOW_LOAD_TAG_MODAL = 'ANO_SHOW_LOAD_TAG_MODAL'
export const ANO_SHOW_UNDELETE_MODAL = 'ANO_SHOW_UNDELETE_MODAL'
export const ANO_TAG_LOAD_STEP_SUCCESS = 'ANO_TAG_LOAD_STEP_SUCCESS'
export const ANO_TAG_LOAD_STEP_FAILURE = 'ANO_TAG_LOAD_STEP_FAILURE'
export const ANO_GO_HOME = 'ANO_GO_HOME'
